### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by rimrul** [jnavila/git-manpages-l10n#27]
We might have a bit of a licensing issue on our hands.

I've stumbled accross this section in `LICENSE.txt`:

> While most of this project is under the GPL (see COPYING), the xdiff/
 library and some libc code from compat/ are licensed under the
 GNU LGPL, version 2.1 or (at your option) any later version and some
 other files are under other licenses.  Check the individual files to
 be sure.

We have no file `COPYING`, no folders `xdiff/` and `compat/` and use neither code from `xdiff` nor `libc` AFAIK.

While github and weblate have pulled from  `LICENSE.txt` that it contains LGPL-2.1, the po files for de, es_MX, fr and ru say:

>This file is distributed under the same license as the Git package.

The other languages say the same thing, but for "the PACKAGE package".

As `LICENSE.txt` indicates most of Git is under the GPL v2. From my understanding that includes the Documentation. You can probably see where this is going.

The proper license file to copy from Git would have probably been `COPYING` instead of `LGPL-2.1`. I'm not sure if we need to contact the contributors about relicensing their contributions. According to the [FSF](https://www.gnu.org/licenses/gpl-faq.html#TranslateCode) translations are derived works, so I think we're legally required to relicense under GPLv2.

They also say in their [Quick Guide to GPLv3](https://www.gnu.org/licenses/quick-guide-gplv3.html)

>Under GPLv2, if you violated the license in any way, your rights were automatically and permanently lost. The only way to get them back was to petition the copyright holder.

I'm not sure if we are in that situation yet. But talking to Junio about this whole situation might not hurt. We should probably clear this up sooner, rather than later.

**Comment by jnavila** [comment]
Ah. As I initially intended to make the translation of the git manpages live inside the git project, the license had obviously to be the same as the one of Git.

Most of the license files are copied from the Git project, but obviously, I made the mistake you are refering to.

Now, LGPL-2.1 is compatible with GPLv2, so this would just mean that this work can be "linked" to applications that are not GPL (e.g. proprietary Git applications), but I really think that this does not make sense at all for the project of translating documentation, which is not a software library per se. Even GPLv2 would not really make sense, but I thinks it's safe.

So, for now, I could simply write an email to all people that have really commited content to this repo and ask them for confirmation of switching to GPLv2. They are not many, if I remove the ones that have only created the file automatically from Weblate.

**Comment by rimrul** [comment]
#36 fixed this repo, and even though it's sad to lose some translation progress, apart from the script-generatable content it was just a couple short sentences. Weblate still shows the LGPL (I think we need to talk to them for a manual update) and didn't remove the languages corresponding to the deleted files or reset their progress. We might have to remove them manually.

**Comment by jnavila** [comment]
The license was updated manually, but it seems languages can not be removed. We might have to reintroduce them from a fresh copy.

**Comment by jnavila** [comment]
That's it.

**Comment by mastizaad** [comment]
fitojb:master
