### ISSUE TITLE
ellipsis errors on weblate

### ISSUE THREAD

**Issue by leela52452** [jnavila/git-manpages-l10n#28]
does it make sense to fix ellipsis errors given on weblate ?
[weblate](https://hosted.weblate.org/projects/git-manpages/translations/source/review/?type=check%3Aellipsis)

**Comment by rimrul** [comment]
Seeing as these are checks on source strings, these would either need to be fixed in git.git or we'd need a patch to make `[update-sources.sh](https://github.com/jnavila/git-manpages-l10n/blob/master/scripts/update-sources.sh)` replace these on every update.

**Comment by rimrul** [comment]
And since `update-sources.sh` uses `ln` we probably shouldn't use that workaround

**Comment by jnavila** [comment]
We can also force `ignore-end-ellipsis` on entries.

**Comment by rimrul** [comment]
I think this should be the ignore-ellipsis flag, as it is for the "Ellipsis" check, as opposed to the "Trailing ellipsis" check
