### ISSUE TITLE
Request for clarification: Ambiguous sections in documentation

### ISSUE THREAD

**Issue by ttdly** [jnavila/git-manpages-l10n#97]
Hello,

I am confused by the description of the `--namespace` option on [this page](https://git-scm.com/docs/git/en).

In the SYNOPSIS section, the `--namespace` option is followed by `<name>`, but in the OPTIONS section, the `--namespace` option is followed by `<path>`. Is there anything wrong with this?"

**Comment by jnavila** [comment]
I think that this is inconsistent. What the original writer means is that the way of organizing the namespaces is to file them in a hierarchy, using the path notation. So for instance, if you have two set of namespaces "developpers" and "integrators", you could create a namespace "developpers/alice" for a given developper and another namespace "integrators/bob" for an integrator. I guess this way of organizing the namespaces fits with the way they are managed on the disk in directory structures. See https://git-scm.com/docs/gitnamespaces for more explanation.

I agree that this mixup is awkward. You can push a patch to fix it to the original git project, if you wish, or just list them here and I'll push them for you (citing you in the commit).

**Comment by ttdly** [comment]
Makes sense, thank you for your clear and detailed explanation. 

And I will attempt to push a patch myself to fix the inconsistencies in the original text, as this will be a new experience for me. If I encounter any difficulties along the way, I may seek your assistance again. Thank you once more for your guidance and for offering to help with the commit on my behalf.

**Comment by ttdly** [comment]
Hello,

In [this](https://hosted.weblate.org/translate/git-manpages/translations/zh_Hans/?q=check:translated) translation,
'Things to Check' it shows 'The following format strings are missing: --message)', but personally, I don’t think the parenthesis ‘)’ at the end of the string is part of the placeholder, is it?

And there are many entries like this one.

**Comment by jnavila** [comment]
Ah, yes. That's true. The regex that captures these words isn't selective enough. I'm going to fix the script and reroll the translation files.

**Comment by ttdly** [comment]
Hello, 

> This documentation discusses repository and command interfaces which
> users are expected to interact with directly. See `--user-formats` in
> linkgit:git-help[1] for more details on the criteria.

This sentence notes that I need to check `--user-formats` in `git-help`, and I checked `git-help` for more details about this option, but I couldn't find the option `--user-formats`.

 By the way, has it changed to `--user-interface` now?

[location of this sentence](https://github.com/jnavila/git-manpages-l10n/blob/master/en/git.txt#L347)

**Comment by jnavila** [comment]
Oh! Good catch! Do you want to submit a patch?

**Comment by ttdly** [comment]
Delighted
