### ISSUE TITLE
Source string problem: slightly broken placeholder

### ISSUE THREAD

**Issue by yajamon** [jnavila/git-manpages-l10n#98]
Hello.

I found a slightly broken placeholder in the source string.

https://github.com/jnavila/git-manpages-l10n/blob/c1cb22232394a6e9bcd9c7b965acf31645e559ff/en/git-clone.txt#L314

**Comment by jnavila** [comment]
Thank you. I found it too. You can propose a patch in the git project (it is quite easy with [gitgitgadget](https://github.com/gitgitgadget/gitgitgadget). Anyway, I'll group all the errors I have found in a patch series after this release.

**Comment by alisam1189** [comment]
Thank you and you are great

**Comment by alisam1189** [comment]
Thank you and you are great
